port 26379
dir "/data"
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel announce-ip "sentinel-3"
sentinel monitor mymaster redis-master 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 60000
