dir "/data"

replicaof redis-master 6379
replica-read-only yes
replica-announce-ip "redis-replica-2"

save 60 1
appendonly yes
appendfsync everysec
auto-aof-rewrite-percentage 100

maxmemory 256mb
maxmemory-policy volatile-lru

min-replicas-to-write 1
min-replicas-max-lag 10
